name: build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: validate gradle-wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build
      id: built
      run: ./gradlew build

    - name: getTag
      id: tag
      run:  |
            echo "MAJ=$(./gradlew -q getMajorVersion)" >> "$GITHUB_OUTPUT"
            echo "MIN=$(./gradlew -q getMinorVersion)" >> "$GITHUB_OUTPUT"
    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*.jar"
        name: Bedrockminer-MC-1.${{ steps.tag.outputs.MAJ }}.${{ steps.tag.outputs.MIN }}
        tag: MC-1.${{ steps.tag.outputs.MAJ }}
        allowUpdates: true
        replacesArtifacts: false
        removeArtifacts: false
